### ISSUE TITLE
Processing(java) port and some suggestions

### ISSUE THREAD

**Issue by buckle2000** [mxgmn/ConvChain#1]
Firstly, this project is amazing and [this is my port in Java](https://github.com/buckle2000/ConvChainJava).

---
Use dictionary (or mapping or whatever) for weights, which is faster.

---
During porting, I found that if a pattern does not have a weight, the default value should be greater than 0 but not 0, which in your case is 0.1 .
I would intepret that this variable specifies how much generated image is like original image (higher -> less similar). You should mention this in your README so other programmers will not fall into this pit.

---
[`Pattern.Index` can be faster](https://github.com/buckle2000/ConvChainJava/blob/2d3c100/src/ConvChain/Pattern.java#L41)

---
The result is not deterministic even if `temperature = 0` in Java but I don't know how it is in C#. There must be floating-point error or problem with infinity and `Math.pow`.

---
I think that this algorithm can accept more than 2 colors. Is that correct?

**Comment by mxgmn** [comment]
Thanks!

Why HashMap though? Index is already a perfect hash function for patterns. Original version doesn't perform any dictionary search at all. Going to a known index in an array is faster than dictionary search.

0.1 is a penalty for not finding a pattern in a sample image. If you take 1 instead than it means no penalties. If you take 0 instead than some probability distributions could collapse to 0.

Yes, potentially it could be extended to colored images. But naive generalization suffers from overfitting. I plan to upgrade it to colored version in the future.

**Comment by buckle2000** [comment]
Though it's faster to index an array, it takes too much memory because it is a **sparse array**. i.e. not all possible patterns can appear in sample.

space complexity from O(2^(N*N)) to O(sample size^2)
access time complexity from O(1) to O(1)

**Comment by mxgmn** [comment]
They are 2 different n s on the left and on the right sides in your space complexity analysis. n on the left is equal to 2 or 3 or maybe 4. n on the right is the size of the input image.

And getting a weight is the most called function in the program.

**Comment by buckle2000** [comment]
You are correct, but still O(2^(N*N)) ≤ O(sample size^2).
